apiVersion: shipwright.io/v1alpha1
kind: Build
metadata:
  name: devsecops-shipwright-tekton
  namespace: devsecops-demo
spec:
  source:
    url: https://github.com/adambkaplan/devsecops-shipwright-tekton
  strategy:
    name: ko
    kind: BuildStrategy
  output:
    image: image-registry.openshift-image-registry.svc:5000/devsecops-demo/devsecops-shipwright-tekton:latest
