apiVersion: shipwright.io/v1alpha1
kind: Build
metadata:
  name: devsecops-shipwright-tekton
  namespace: cdcon-demo-ci
spec:
  source:
    url: https://github.com/adambkaplan/devsecops-shipwright-tekton
  strategy:
    name: ko
    kind: ClusterBuildStrategy
  output:
    image: image-registry.openshift-image-registry.svc:5000/cdcon-demo-ci/devsecops-shipwright-tekton:latest
