apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: simple-pipeline
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "[git-clone, golang-test, golang-build]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
  params:
  - name: repo_url
    value: "{{repo_url}}"
  - name: revision
    value: "{{revision}}"
  - name: golang-version
    value: "1.17.7"
  pipelineSpec:
    workspaces:
    - name: source
    params:
    - name: repo_url
    - name: revision
    - name: golang-version
    tasks:
    - name: git-clone
      params:
      - name: url
        value: $(params.repo_url)
      - name: revision
        value: $(params.revision)
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: source
    - name: test
      runAfter: [git-clone]
      params:
      - name: version
        value: $(params.golang-version)
      - name: package
        value: github.com/adambkaplan/devsecops-shipwright-tekton
      - name: packages
        value: "./..."
      taskRef:
        name: golang-test
      workspaces:
      - name: source
        workspace: source
